### ISSUE TITLE
Issues downloading database for tension and touchstone board

### ISSUE THREAD

**Issue by YamaKan77** [lemeryfertitta/BoardLib#46]
I've been trying to download the database of tension and touchstone board climbs but have been getting errors about a SSL error.

Running this command `boardlib database touchstone touchstone.db`

`Downloading database to touchstone.db
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Python312\Lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Python312\Lib\ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='d-05.winudf.com', port=443): Max retries exceeded with url: /b/APK/Y29tLmF1cm9yYWNsaW1iaW5nLnRvdWNoc3RvbmVib2FyZF8xOTNfNGI5ZTFhOA?_fn=VG91Y2hzdG9uZSBCb2FyZF8zLjQuMTRfQVBLUHVyZS5hcGs&_p=Y29tLmF1cm9yYWNsaW1iaW5nLnRvdWNoc3RvbmVib2FyZA%3D%3D&is_hot=false&k=64c4e914770b2585c9496551de274fec66e1155b (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\boardlib.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\boardlib\__main__.py", line 134, in main
    args.func(args)
  File "C:\Python312\Lib\site-packages\boardlib\__main__.py", line 45, in handle_database_command
    boardlib.db.aurora.download_database(args.board, args.database_path)
  File "C:\Python312\Lib\site-packages\boardlib\db\aurora.py", line 29, in download_database
    response = requests.get(
               ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\sessions.py", line 724, in send
    history = [resp for resp in gen]
                                ^^^
  File "C:\Python312\Lib\site-packages\requests\sessions.py", line 265, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='d-05.winudf.com', port=443): Max retries exceeded with url: /b/APK/Y29tLmF1cm9yYWNsaW1iaW5nLnRvdWNoc3RvbmVib2FyZF8xOTNfNGI5ZTFhOA?_fn=VG91Y2hzdG9uZSBCb2FyZF8zLjQuMTRfQVBLUHVyZS5hcGs&_p=Y29tLmF1cm9yYWNsaW1iaW5nLnRvdWNoc3RvbmVib2FyZA%3D%3D&is_hot=false&k=64c4e914770b2585c9496551de274fec66e1155b (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))`

**Comment by lemeryfertitta** [comment]
I am not able to reproduce this issue. The command you posted works for me without error.

My guess would be that either your local env is incorrect (maybe different versions of requests and/or urllib3?) or the APK host was having temporary SSL issues.
